import type { LearningResource } from '@/lib/types';

/**
 * Curated resource library.
 *
 * HONESTY RULE — read before editing
 * ----------------------------------
 * `verification` defaults to `'pending'` and `lastReviewed` to `null`, and every
 * entry below ships that way. These links were selected from knowledge of the
 * providers, but none has been opened and checked by a human during
 * implementation. Claiming otherwise would be a lie to a user with limited data
 * who is about to spend it on a broken link.
 *
 * Only a person who has actually opened the link, confirmed the content is
 * present, free, and roughly as described, may set `verification: 'verified'`
 * and a real `lastReviewed` date — or do it through the admin screen, which
 * stamps the date automatically.
 *
 * See docs/CONTENT_MODEL.md.
 */

type ResourceSeed = Omit<LearningResource, 'verification' | 'lastReviewed' | 'archived'> &
  Partial<Pick<LearningResource, 'verification' | 'lastReviewed' | 'archived'>>;

function defineResource(seed: ResourceSeed): LearningResource {
  return {
    verification: 'pending',
    lastReviewed: null,
    archived: false,
    ...seed,
  };
}

export const resources: LearningResource[] = [
  // ===========================================================================
  // Digital literacy
  // ===========================================================================
  defineResource({
    id: 'res-gcf-informatique',
    title: 'Les bases de l’informatique',
    provider: 'GCFGlobal',
    url: 'https://edu.gcfglobal.org/fr/tema/informatique-de-base/',
    description:
      'Cours illustrés pour comprendre un ordinateur, le système d’exploitation, les fenêtres et les périphériques. Écrit simplement, pages légères.',
    language: 'fr',
    skillIds: ['informatique-base', 'fichiers-dossiers'],
    sectorIds: ['numerique'],
    format: 'cours',
    level: 'debutant',
    minutes: 240,
    connectivity: 'low',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Le meilleur point de départ pour quelqu’un qui n’a jamais utilisé d’ordinateur. Pages textuelles, peu de vidéo, donc peu de données consommées.',
  }),
  defineResource({
    id: 'res-gcf-internet',
    title: 'Utiliser Internet en sécurité',
    provider: 'GCFGlobal',
    url: 'https://edu.gcfglobal.org/fr/tema/internet/',
    description:
      'Navigation, moteurs de recherche, comptes en ligne, reconnaissance des arnaques et protection des mots de passe.',
    language: 'fr',
    skillIds: ['recherche-web', 'securite-numerique'],
    sectorIds: ['numerique'],
    format: 'cours',
    level: 'debutant',
    minutes: 180,
    connectivity: 'low',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes: 'Utile en particulier pour la partie arnaques et sécurité des comptes.',
  }),
  defineResource({
    id: 'res-lesbonsclics',
    title: 'Les Bons Clics — ateliers numériques',
    provider: 'Les Bons Clics (WeTechCare)',
    url: 'https://www.lesbonsclics.fr/',
    description:
      'Fiches et exercices d’inclusion numérique en français simple : e-mail, formulaires en ligne, sécurité, démarches.',
    language: 'fr',
    skillIds: ['informatique-base', 'email-pro', 'securite-numerique'],
    sectorIds: ['numerique'],
    format: 'exercice',
    level: 'debutant',
    minutes: 120,
    connectivity: 'low',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Conçu pour des personnes très éloignées du numérique. Certains contenus font référence à des démarches françaises : ignorez-les, la méthode reste valable.',
  }),
  defineResource({
    id: 'res-gcf-word',
    title: 'Traitement de texte — Word',
    provider: 'GCFGlobal',
    url: 'https://edu.gcfglobal.org/fr/tema/word/',
    description:
      'Créer, mettre en forme, enregistrer et exporter un document professionnel.',
    language: 'fr',
    skillIds: ['traitement-texte', 'communication-ecrite'],
    sectorIds: ['administration', 'numerique'],
    format: 'cours',
    level: 'debutant',
    minutes: 180,
    connectivity: 'low',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes: 'Les principes s’appliquent aussi à LibreOffice Writer et Google Docs.',
  }),
  defineResource({
    id: 'res-gcf-excel',
    title: 'Tableur — Excel',
    provider: 'GCFGlobal',
    url: 'https://edu.gcfglobal.org/fr/tema/excel/',
    description:
      'Saisie, formules, tri, filtres et mise en forme. La compétence la plus fréquemment demandée dans les postes de support.',
    language: 'fr',
    skillIds: ['tableur', 'suivi-resultats'],
    sectorIds: ['administration', 'finance', 'logistique', 'mines'],
    format: 'cours',
    level: 'debutant',
    minutes: 300,
    connectivity: 'low',
    mobileFriendly: false,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'À suivre sur ordinateur : Excel se pratique mal sur téléphone. Un cybercafé ou un poste partagé suffit.',
  }),
  defineResource({
    id: 'res-exceleasy',
    title: 'Excel Easy — tutoriels et exemples',
    provider: 'Excel Easy',
    url: 'https://www.excel-easy.com/',
    description:
      'Tutoriels courts et concrets, fonction par fonction, avec des fichiers d’exemple.',
    language: 'en',
    skillIds: ['tableur'],
    sectorIds: ['administration', 'finance', 'logistique'],
    format: 'guide',
    level: 'intermediaire',
    minutes: 240,
    connectivity: 'low',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'En anglais, mais le vocabulaire d’Excel est de toute façon en anglais dans beaucoup d’entreprises. Bon double usage : tableur et anglais technique.',
  }),
  defineResource({
    id: 'res-microsoft-learn-excel',
    title: 'Formation Excel',
    provider: 'Microsoft Learn',
    url: 'https://support.microsoft.com/fr-fr/office/formation-excel-9bc05390-e94c-46af-a5b3-d7c22f6990bb',
    description: 'Parcours officiel Microsoft, du démarrage aux tableaux croisés dynamiques.',
    language: 'fr',
    skillIds: ['tableur'],
    sectorIds: ['administration', 'finance'],
    format: 'cours',
    level: 'intermediaire',
    minutes: 300,
    connectivity: 'medium',
    mobileFriendly: false,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes: 'Contient beaucoup de vidéos : prévoyez du forfait ou une connexion wifi.',
  }),
  defineResource({
    id: 'res-gcf-powerpoint',
    title: 'Présentations — PowerPoint',
    provider: 'GCFGlobal',
    url: 'https://edu.gcfglobal.org/fr/tema/powerpoint/',
    description: 'Construire un diaporama lisible et le présenter correctement.',
    language: 'fr',
    skillIds: ['presentation-outil', 'presentation-orale'],
    sectorIds: ['administration', 'communication'],
    format: 'cours',
    level: 'debutant',
    minutes: 120,
    connectivity: 'low',
    mobileFriendly: false,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes: 'Applicable à Google Slides et LibreOffice Impress.',
  }),
  defineResource({
    id: 'res-google-ateliers',
    title: 'Ateliers Numériques',
    provider: 'Google',
    url: 'https://learndigital.withgoogle.com/ateliersnumeriques',
    description:
      'Modules gratuits sur la communication numérique, le marketing en ligne et les bases du travail à distance.',
    language: 'fr',
    skillIds: ['marketing-digital', 'recherche-web', 'cloud-docs'],
    sectorIds: ['numerique', 'communication', 'entrepreneuriat'],
    format: 'cours',
    level: 'debutant',
    minutes: 360,
    connectivity: 'high',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: true,
    qualityNotes:
      'Attestation gratuite sur certains parcours. Contenu très vidéo : à réserver aux moments de bonne connexion.',
  }),
  defineResource({
    id: 'res-pix',
    title: 'Pix — évaluer ses compétences numériques',
    provider: 'Pix',
    url: 'https://pix.org/',
    description:
      'Test en ligne qui situe votre niveau numérique par domaine et propose des exercices ciblés.',
    language: 'fr',
    skillIds: ['informatique-base', 'recherche-web', 'securite-numerique'],
    sectorIds: ['numerique'],
    format: 'exercice',
    level: 'debutant',
    minutes: 120,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: true,
    qualityNotes:
      'La certification officielle est destinée au public français, mais le test d’auto-évaluation est utile partout.',
  }),
  defineResource({
    id: 'res-cybermalveillance',
    title: 'Bonnes pratiques de sécurité numérique',
    provider: 'Cybermalveillance.gouv.fr',
    url: 'https://www.cybermalveillance.gouv.fr/tous-nos-contenus',
    description:
      'Fiches courtes et téléchargeables sur les mots de passe, l’hameçonnage et les arnaques les plus fréquentes.',
    language: 'fr',
    skillIds: ['securite-numerique'],
    sectorIds: ['numerique'],
    format: 'guide',
    level: 'debutant',
    minutes: 60,
    connectivity: 'offline',
    mobileFriendly: true,
    offlineCapable: true,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Fiches PDF téléchargeables : parfait pour consulter hors ligne après un seul téléchargement.',
  }),

  // ===========================================================================
  // English
  // ===========================================================================
  defineResource({
    id: 'res-bbc-learning-english',
    title: 'BBC Learning English',
    provider: 'BBC',
    url: 'https://www.bbc.co.uk/learningenglish',
    description:
      'Leçons quotidiennes, vocabulaire, grammaire et compréhension orale, du niveau débutant au niveau avancé.',
    language: 'en',
    skillIds: ['anglais-pro'],
    sectorIds: ['langues'],
    format: 'cours',
    level: 'debutant',
    minutes: 600,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'La référence gratuite. Les transcriptions écrites permettent de travailler sans écouter les audios quand la connexion est faible.',
  }),
  defineResource({
    id: 'res-british-council',
    title: 'LearnEnglish',
    provider: 'British Council',
    url: 'https://learnenglish.britishcouncil.org/',
    description:
      'Cours structurés par niveau, exercices de grammaire et anglais professionnel.',
    language: 'en',
    skillIds: ['anglais-pro', 'anglais-entretien'],
    sectorIds: ['langues'],
    format: 'cours',
    level: 'debutant',
    minutes: 600,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes: 'La section « Business and work » correspond directement aux attentes des employeurs.',
  }),
  defineResource({
    id: 'res-voa-learning-english',
    title: 'VOA Learning English',
    provider: 'Voice of America',
    url: 'https://learningenglish.voanews.com/',
    description:
      'Actualités lues lentement, avec transcription. Excellent pour l’écoute quand on débute.',
    language: 'en',
    skillIds: ['anglais-pro'],
    sectorIds: ['langues'],
    format: 'podcast',
    level: 'debutant',
    minutes: 300,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: true,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Les audios sont téléchargeables : téléchargez plusieurs épisodes en wifi puis écoutez hors ligne.',
  }),
  defineResource({
    id: 'res-duolingo',
    title: 'Duolingo — anglais depuis le français',
    provider: 'Duolingo',
    url: 'https://www.duolingo.com/',
    description: 'Application d’apprentissage par courtes sessions quotidiennes.',
    language: 'multi',
    skillIds: ['anglais-pro'],
    sectorIds: ['langues'],
    format: 'exercice',
    level: 'debutant',
    minutes: 300,
    connectivity: 'low',
    mobileFriendly: true,
    offlineCapable: true,
    cost: 'freemium',
    certificate: false,
    qualityNotes:
      'Bon pour le vocabulaire de base et la régularité ; insuffisant seul pour l’anglais professionnel. La version gratuite affiche de la publicité. Utilise des mécaniques de série quotidienne : gardez-les à votre service, pas l’inverse.',
  }),
  defineResource({
    id: 'res-business-english-pod',
    title: 'Business English Pod',
    provider: 'Business English Pod',
    url: 'https://www.businessenglishpod.com/',
    description:
      'Leçons audio sur les réunions, les appels, les négociations et les entretiens en anglais.',
    language: 'en',
    skillIds: ['anglais-pro', 'anglais-entretien', 'communication-orale'],
    sectorIds: ['langues', 'commerce'],
    format: 'podcast',
    level: 'intermediaire',
    minutes: 420,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: true,
    cost: 'freemium',
    certificate: false,
    qualityNotes: 'Une partie des leçons est gratuite. Le reste est payant : rien d’indispensable.',
  }),
  defineResource({
    id: 'res-esl-lab',
    title: 'Randall’s ESL Cyber Listening Lab',
    provider: 'esl-lab.com',
    url: 'https://www.esl-lab.com/',
    description:
      'Exercices d’écoute classés par difficulté, avec questions de compréhension et transcription.',
    language: 'en',
    skillIds: ['anglais-pro'],
    sectorIds: ['langues'],
    format: 'exercice',
    level: 'debutant',
    minutes: 240,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes: 'Audios courts et légers, adaptés à une connexion modeste.',
  }),
  defineResource({
    id: 'res-tv5-apprendre',
    title: 'Apprendre le français',
    provider: 'TV5MONDE',
    url: 'https://apprendre.tv5monde.com/',
    description:
      'Exercices de français par niveau à partir de vidéos courtes, dont une section français professionnel.',
    language: 'fr',
    skillIds: ['francais-pro', 'communication-ecrite'],
    sectorIds: ['langues'],
    format: 'exercice',
    level: 'debutant',
    minutes: 300,
    connectivity: 'high',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Très utile pour renforcer l’écrit professionnel. Consomme des données : privilégiez le wifi.',
  }),
  defineResource({
    id: 'res-rfi-savoirs',
    title: 'RFI Savoirs — français professionnel',
    provider: 'RFI',
    url: 'https://savoirs.rfi.fr/',
    description:
      'Ressources audio et écrites pour progresser en français, avec un volet vie professionnelle.',
    language: 'fr',
    skillIds: ['francais-pro', 'communication-orale'],
    sectorIds: ['langues'],
    format: 'podcast',
    level: 'intermediaire',
    minutes: 240,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: true,
    cost: 'gratuit',
    certificate: false,
    qualityNotes: 'Audios téléchargeables, adaptés à une écoute hors ligne.',
  }),

  // ===========================================================================
  // Commercial and sales
  // ===========================================================================
  defineResource({
    id: 'res-hubspot-academy-vente',
    title: 'HubSpot Academy — cours de vente',
    provider: 'HubSpot Academy',
    url: 'https://academy.hubspot.com/courses',
    description:
      'Cours gratuits sur la prospection, la découverte du besoin, le suivi et l’usage d’un CRM.',
    language: 'multi',
    skillIds: ['vente-techniques', 'prospection', 'crm', 'relation-client'],
    sectorIds: ['commerce'],
    format: 'cours',
    level: 'intermediaire',
    minutes: 480,
    connectivity: 'high',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: true,
    qualityNotes:
      'Attestations gratuites reconnues. Certains cours existent en français, la plupart sont en anglais : bon entraînement double.',
  }),
  defineResource({
    id: 'res-trailhead-vente',
    title: 'Trailhead — modules de vente et CRM',
    provider: 'Salesforce',
    url: 'https://trailhead.salesforce.com/',
    description:
      'Modules courts et gratuits sur la relation client, le pipeline commercial et l’usage d’un CRM.',
    language: 'multi',
    skillIds: ['crm', 'relation-client', 'suivi-resultats'],
    sectorIds: ['commerce', 'numerique'],
    format: 'cours',
    level: 'intermediaire',
    minutes: 360,
    connectivity: 'high',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: true,
    qualityNotes:
      'Interface partiellement traduite en français. Les badges obtenus peuvent être cités dans un CV.',
  }),
  defineResource({
    id: 'res-openclassrooms-prospection',
    title: 'OpenClassrooms — cours de vente et prospection',
    provider: 'OpenClassrooms',
    url: 'https://openclassrooms.com/fr/courses',
    description:
      'Catalogue de cours en français, dont plusieurs sur la prospection, la négociation et la relation client.',
    language: 'fr',
    skillIds: ['prospection', 'negociation', 'vente-techniques', 'strategie-commerciale'],
    sectorIds: ['commerce'],
    format: 'cours',
    level: 'intermediaire',
    minutes: 480,
    connectivity: 'high',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'freemium',
    certificate: false,
    qualityNotes:
      'La lecture des cours est gratuite ; la certification est payante. Vérifiez le prix affiché avant de vous engager.',
  }),
  defineResource({
    id: 'res-fun-mooc',
    title: 'FUN-MOOC — cours universitaires francophones',
    provider: 'France Université Numérique',
    url: 'https://www.fun-mooc.fr/',
    description:
      'MOOC gratuits en français : gestion, entrepreneuriat, numérique, communication professionnelle.',
    language: 'fr',
    skillIds: ['strategie-commerciale', 'budget', 'pensee-critique'],
    sectorIds: ['commerce', 'finance', 'entrepreneuriat'],
    format: 'cours',
    level: 'intermediaire',
    minutes: 900,
    connectivity: 'high',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: true,
    qualityNotes:
      'Les cours ouvrent à des dates fixes. Vérifiez le calendrier ; certains restent consultables en archive.',
  }),

  // ===========================================================================
  // Mining sector and support functions
  // ===========================================================================
  defineResource({
    id: 'res-itie-mali',
    title: 'ITIE Mali — rapports du secteur extractif',
    provider: 'Initiative pour la Transparence des Industries Extractives',
    url: 'https://eiti.org/fr/pays/mali',
    description:
      'Rapports publics sur les sociétés minières actives au Mali, leur production et leurs contributions.',
    language: 'fr',
    skillIds: ['mines-connaissance', 'environnement-social', 'recherche-web'],
    sectorIds: ['mines'],
    format: 'article',
    level: 'intermediaire',
    minutes: 120,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: true,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Source de référence pour identifier les entreprises du secteur et préparer une recherche employeur. Rapports téléchargeables en PDF.',
  }),
  defineResource({
    id: 'res-icmm',
    title: 'ICMM — pratiques du secteur minier',
    provider: 'International Council on Mining and Metals',
    url: 'https://www.icmm.com/',
    description:
      'Documents de référence sur la sécurité, l’environnement et les relations avec les communautés dans l’industrie minière.',
    language: 'en',
    skillIds: ['mines-connaissance', 'hse', 'environnement-social', 'anglais-pro'],
    sectorIds: ['mines'],
    format: 'article',
    level: 'avance',
    minutes: 180,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: true,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'En anglais et assez technique. À utiliser pour comprendre le vocabulaire employé par les grands opérateurs.',
  }),
  defineResource({
    id: 'res-ilo-osh',
    title: 'Sécurité et santé au travail',
    provider: 'Organisation internationale du Travail',
    url: 'https://www.ilo.org/fr/themes/securite-et-sante-au-travail',
    description:
      'Principes de prévention des risques professionnels, équipements de protection et culture de sécurité.',
    language: 'fr',
    skillIds: ['hse'],
    sectorIds: ['mines', 'logistique', 'agriculture'],
    format: 'guide',
    level: 'debutant',
    minutes: 120,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: true,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Sensibilisation générale uniquement. Ne remplace aucune formation de sécurité obligatoire sur site.',
  }),
  defineResource({
    id: 'res-chambre-mines-mali',
    title: 'Chambre des Mines du Mali',
    provider: 'Chambre des Mines du Mali',
    url: 'https://www.chambredesmines.ml/',
    description:
      'Organisation professionnelle du secteur minier malien : membres, actualités, cadre du secteur.',
    language: 'fr',
    skillIds: ['mines-connaissance', 'recherche-web'],
    sectorIds: ['mines'],
    format: 'article',
    level: 'debutant',
    minutes: 60,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Point de départ pour identifier les entreprises et sous-traitants du secteur avant une candidature.',
  }),
  defineResource({
    id: 'res-anpe-mali',
    title: 'ANPE Mali — Agence Nationale pour l’Emploi',
    provider: 'ANPE Mali',
    url: 'https://www.anpe-mali.org/',
    description:
      'Service public de l’emploi malien : offres, dispositifs d’insertion et accompagnement des demandeurs.',
    language: 'fr',
    skillIds: ['analyse-offre'],
    sectorIds: ['administration', 'commerce'],
    format: 'outil',
    level: 'debutant',
    minutes: 60,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Institution publique de référence au Mali. Vérifiez les modalités d’inscription directement auprès d’une agence.',
  }),
  defineResource({
    id: 'res-apej-mali',
    title: 'APEJ — Agence pour la Promotion de l’Emploi des Jeunes',
    provider: 'APEJ Mali',
    url: 'https://www.apej.ml/',
    description:
      'Dispositifs publics maliens destinés aux jeunes : stages, financements, appui à l’auto-emploi.',
    language: 'fr',
    skillIds: ['analyse-offre', 'test-idee'],
    sectorIds: ['entrepreneuriat', 'administration'],
    format: 'outil',
    level: 'debutant',
    minutes: 60,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'À contacter directement : les dispositifs et leurs conditions évoluent régulièrement.',
  }),

  // ===========================================================================
  // Employment preparation
  // ===========================================================================
  defineResource({
    id: 'res-indeed-guide-cv',
    title: 'Guide de carrière — CV et lettres',
    provider: 'Indeed',
    url: 'https://fr.indeed.com/conseils-carrieres',
    description:
      'Articles pratiques sur la rédaction du CV, la lettre de motivation et la préparation des entretiens.',
    language: 'fr',
    skillIds: ['communication-ecrite', 'analyse-offre'],
    sectorIds: ['administration', 'commerce'],
    format: 'article',
    level: 'debutant',
    minutes: 120,
    connectivity: 'low',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Contenu orienté marché français ; les principes de rédaction restent valables. Ignorez les références aux dispositifs français.',
  }),
  defineResource({
    id: 'res-wttj-entretien',
    title: 'Conseils entretien et vie professionnelle',
    provider: 'Welcome to the Jungle',
    url: 'https://www.welcometothejungle.com/fr/collections',
    description:
      'Articles sur la préparation d’entretien, les questions difficiles et les codes du monde du travail.',
    language: 'fr',
    skillIds: ['confiance', 'communication-orale', 'analyse-offre'],
    sectorIds: ['commerce', 'administration'],
    format: 'article',
    level: 'debutant',
    minutes: 120,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes: 'Ton moderne et concret. Pages riches en images : consomme des données.',
  }),
  defineResource({
    id: 'res-europass-cv',
    title: 'Europass — créateur de CV',
    provider: 'Union européenne',
    url: 'https://europa.eu/europass/fr',
    description:
      'Outil gratuit pour rédiger un CV structuré et l’exporter en PDF, sans logiciel installé.',
    language: 'fr',
    skillIds: ['communication-ecrite', 'traitement-texte'],
    sectorIds: ['administration'],
    format: 'outil',
    level: 'debutant',
    minutes: 90,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Format très standard, parfois jugé rigide par certains recruteurs. Utile quand on part de zéro.',
  }),
  defineResource({
    id: 'res-canva-cv',
    title: 'Modèles de CV',
    provider: 'Canva',
    url: 'https://www.canva.com/fr_fr/cv/modeles/',
    description: 'Modèles de CV modifiables en ligne et exportables en PDF.',
    language: 'fr',
    skillIds: ['traitement-texte', 'presentation-outil'],
    sectorIds: ['administration', 'communication'],
    format: 'modele',
    level: 'debutant',
    minutes: 60,
    connectivity: 'high',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'freemium',
    certificate: false,
    qualityNotes:
      'Beaucoup de modèles gratuits, certains payants. Évitez les designs trop chargés : la lisibilité prime.',
  }),
  defineResource({
    id: 'res-star-method',
    title: 'La méthode STAR expliquée',
    provider: 'Indeed',
    url: 'https://fr.indeed.com/conseils-carrieres/entretiens/methode-star',
    description:
      'Explication détaillée de la structure Situation, Tâche, Action, Résultat avec des exemples.',
    language: 'fr',
    skillIds: ['communication-orale', 'confiance'],
    sectorIds: ['commerce', 'administration'],
    format: 'article',
    level: 'debutant',
    minutes: 30,
    connectivity: 'low',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes: 'Article court, à lire une fois puis à pratiquer.',
  }),

  // ===========================================================================
  // Entrepreneurship
  // ===========================================================================
  defineResource({
    id: 'res-ilo-siyb',
    title: 'Créez et gérez votre entreprise (GERME / SIYB)',
    provider: 'Organisation internationale du Travail',
    url: 'https://www.ilo.org/fr/publications',
    description:
      'Programme de référence de l’OIT pour la création et la gestion de petites entreprises, très utilisé en Afrique de l’Ouest.',
    language: 'fr',
    skillIds: ['test-idee', 'budget', 'tenue-registres', 'pricing'],
    sectorIds: ['entrepreneuriat'],
    format: 'guide',
    level: 'debutant',
    minutes: 480,
    connectivity: 'medium',
    mobileFriendly: false,
    offlineCapable: true,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Certains supports sont diffusés via des organismes de formation locaux plutôt qu’en téléchargement direct. Cherchez « GERME » ou « SIYB » avec le nom d’une structure d’appui au Mali.',
  }),
  defineResource({
    id: 'res-strategyzer-vpc',
    title: 'Canevas de proposition de valeur',
    provider: 'Strategyzer',
    url: 'https://www.strategyzer.com/library',
    description:
      'Outil visuel pour relier ce que vit un client à ce que propose votre offre.',
    language: 'en',
    skillIds: ['proposition-valeur', 'etude-besoin'],
    sectorIds: ['entrepreneuriat', 'commerce'],
    format: 'outil',
    level: 'intermediaire',
    minutes: 90,
    connectivity: 'medium',
    mobileFriendly: false,
    offlineCapable: true,
    cost: 'freemium',
    certificate: false,
    qualityNotes:
      'Le canevas se dessine très bien sur une feuille de papier : téléchargez-le une fois, travaillez hors ligne.',
  }),
  defineResource({
    id: 'res-kiva-guides',
    title: 'Comprendre le microcrédit',
    provider: 'Kiva',
    url: 'https://www.kiva.org/',
    description:
      'Explications sur le fonctionnement du microcrédit et des financements de petites activités.',
    language: 'en',
    skillIds: ['budget', 'tenue-registres'],
    sectorIds: ['entrepreneuriat', 'finance'],
    format: 'article',
    level: 'debutant',
    minutes: 60,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Utile pour comprendre les mécanismes. Pour un financement réel au Mali, adressez-vous aux institutions de microfinance locales.',
  }),

  // ===========================================================================
  // Freelancing and remote work
  // ===========================================================================
  defineResource({
    id: 'res-upwork-guides',
    title: 'Guides pour débuter en freelance',
    provider: 'Upwork Resource Center',
    url: 'https://www.upwork.com/resources',
    description:
      'Articles sur la construction d’un profil, la rédaction de propositions et la relation client à distance.',
    language: 'en',
    skillIds: ['freelance-proposition', 'portfolio', 'anglais-pro'],
    sectorIds: ['numerique', 'entrepreneuriat'],
    format: 'article',
    level: 'intermediaire',
    minutes: 180,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Écrit par une plateforme qui a intérêt à vous y inscrire : lisez la méthode, gardez votre esprit critique sur les promesses de revenus.',
  }),
  defineResource({
    id: 'res-remote-work-guide',
    title: 'Travailler à distance — bonnes pratiques',
    provider: 'GitLab Handbook (Remote)',
    url: 'https://handbook.gitlab.com/handbook/company/culture/all-remote/',
    description:
      'Référence publique et détaillée sur l’organisation du travail à distance : communication écrite, autonomie, réunions.',
    language: 'en',
    skillIds: ['gestion-temps', 'communication-ecrite', 'visio', 'anglais-pro'],
    sectorIds: ['numerique'],
    format: 'guide',
    level: 'intermediaire',
    minutes: 180,
    connectivity: 'low',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes: 'Très long : lisez les sections communication et autonomie en priorité.',
  }),
  defineResource({
    id: 'res-anti-arnaque-freelance',
    title: 'Reconnaître les arnaques au travail en ligne',
    provider: 'Federal Trade Commission (consumer.ftc.gov)',
    url: 'https://consumer.ftc.gov/articles/job-scams',
    description:
      'Signes caractéristiques des fausses offres d’emploi et des arnaques au paiement anticipé.',
    language: 'en',
    skillIds: ['securite-numerique', 'pensee-critique'],
    sectorIds: ['numerique', 'entrepreneuriat'],
    format: 'article',
    level: 'debutant',
    minutes: 30,
    connectivity: 'low',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Règle universelle à retenir : un employeur sérieux ne demande jamais d’argent pour vous embaucher.',
  }),

  // ===========================================================================
  // Soft skills, confidence, thinking
  // ===========================================================================
  defineResource({
    id: 'res-mindtools-communication',
    title: 'Compétences de communication',
    provider: 'Mind Tools',
    url: 'https://www.mindtools.com/',
    description:
      'Fiches pratiques sur l’écoute active, la communication en équipe, la gestion du temps et la résolution de problèmes.',
    language: 'en',
    skillIds: ['ecoute-active', 'communication-orale', 'gestion-temps', 'resolution-problemes'],
    sectorIds: ['communication'],
    format: 'guide',
    level: 'intermediaire',
    minutes: 240,
    connectivity: 'low',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'freemium',
    certificate: false,
    qualityNotes: 'Une partie du contenu est réservée aux abonnés. Les fiches gratuites suffisent.',
  }),
  defineResource({
    id: 'res-ted-talks-confiance',
    title: 'Conférences sur la confiance et la prise de parole',
    provider: 'TED',
    url: 'https://www.ted.com/topics/public+speaking',
    description:
      'Conférences courtes sous-titrées en français sur la confiance, la prise de parole et la persuasion.',
    language: 'multi',
    skillIds: ['confiance', 'presentation-orale', 'communication-orale'],
    sectorIds: ['communication'],
    format: 'video',
    level: 'debutant',
    minutes: 120,
    connectivity: 'high',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Vidéo : consommation de données importante. Les transcriptions écrites sont disponibles et bien plus légères.',
  }),
  defineResource({
    id: 'res-openlearn',
    title: 'OpenLearn — cours ouverts',
    provider: 'The Open University',
    url: 'https://www.open.edu/openlearn/',
    description:
      'Cours universitaires gratuits, dont des modules sur le travail en équipe, la gestion et la communication.',
    language: 'en',
    skillIds: ['travail-equipe', 'gestion-equipe', 'pensee-critique', 'anglais-pro'],
    sectorIds: ['administration', 'commerce'],
    format: 'cours',
    level: 'intermediaire',
    minutes: 600,
    connectivity: 'low',
    mobileFriendly: true,
    offlineCapable: true,
    cost: 'gratuit',
    certificate: true,
    qualityNotes:
      'Nombreux cours téléchargeables en PDF ou EPUB pour une lecture hors ligne. Attestation de participation gratuite.',
  }),
  defineResource({
    id: 'res-khan-academy',
    title: 'Khan Academy en français',
    provider: 'Khan Academy',
    url: 'https://fr.khanacademy.org/',
    description:
      'Cours gratuits de mathématiques et de raisonnement, utiles pour les tests de recrutement.',
    language: 'fr',
    skillIds: ['pensee-critique', 'resolution-problemes'],
    sectorIds: ['finance', 'numerique'],
    format: 'cours',
    level: 'debutant',
    minutes: 480,
    connectivity: 'high',
    mobileFriendly: true,
    offlineCapable: true,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'L’application mobile permet de télécharger des leçons pour une utilisation hors ligne.',
  }),
  defineResource({
    id: 'res-alison',
    title: 'Alison — cours professionnels gratuits',
    provider: 'Alison',
    url: 'https://alison.com/',
    description:
      'Catalogue de cours gratuits avec attestation payante : vente, bureautique, gestion, anglais.',
    language: 'en',
    skillIds: ['vente-techniques', 'tableur', 'gestion-equipe', 'anglais-pro'],
    sectorIds: ['commerce', 'administration'],
    format: 'cours',
    level: 'debutant',
    minutes: 600,
    connectivity: 'high',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'freemium',
    certificate: true,
    qualityNotes:
      'Les cours sont gratuits mais financés par la publicité, et l’attestation est payante. Qualité variable selon les auteurs.',
  }),
  defineResource({
    id: 'res-coursera-audit',
    title: 'Coursera — consultation gratuite des cours',
    provider: 'Coursera',
    url: 'https://www.coursera.org/',
    description:
      'Cours d’universités et d’entreprises, consultables gratuitement en mode audit sur de nombreux programmes.',
    language: 'multi',
    skillIds: ['vente-techniques', 'gestion-equipe', 'tableur', 'anglais-pro'],
    sectorIds: ['commerce', 'administration', 'numerique'],
    format: 'cours',
    level: 'intermediaire',
    minutes: 900,
    connectivity: 'high',
    mobileFriendly: true,
    offlineCapable: true,
    cost: 'freemium',
    certificate: true,
    qualityNotes:
      'Le mode audit donne accès aux vidéos et lectures sans payer ; le certificat est payant. Des aides financières existent et se demandent en ligne. L’application mobile permet le téléchargement hors ligne.',
  }),
  defineResource({
    id: 'res-libreoffice-doc',
    title: 'LibreOffice — documentation et guides',
    provider: 'The Document Foundation',
    url: 'https://documentation.libreoffice.org/fr/documentation-en-francais/',
    description:
      'Guides complets et gratuits d’une suite bureautique libre, installable sans licence payante.',
    language: 'fr',
    skillIds: ['traitement-texte', 'tableur', 'presentation-outil'],
    sectorIds: ['administration', 'numerique'],
    format: 'guide',
    level: 'debutant',
    minutes: 300,
    connectivity: 'offline',
    mobileFriendly: false,
    offlineCapable: true,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'Solution recommandée quand on n’a pas de licence Microsoft Office. Guides en PDF, consultables hors ligne.',
  }),
  defineResource({
    id: 'res-mooc-francophone-comm',
    title: 'Ressources de communication professionnelle',
    provider: 'Agence universitaire de la Francophonie',
    url: 'https://www.auf.org/',
    description:
      'Programmes et ressources de formation francophones, dont des modules d’employabilité et de communication.',
    language: 'fr',
    skillIds: ['communication-ecrite', 'francais-pro', 'presentation-orale'],
    sectorIds: ['langues', 'administration'],
    format: 'cours',
    level: 'intermediaire',
    minutes: 240,
    connectivity: 'medium',
    mobileFriendly: true,
    offlineCapable: false,
    cost: 'gratuit',
    certificate: false,
    qualityNotes:
      'L’offre varie selon les campus numériques. Vérifiez les programmes ouverts au Mali.',
  }),
];

export const resourceById = new Map(resources.map((resource) => [resource.id, resource]));

export function resourcesByIds(ids: readonly string[]): LearningResource[] {
  return ids
    .map((id) => resourceById.get(id))
    .filter((resource): resource is LearningResource => Boolean(resource));
}
