-- =============================================================================
-- 0001_schema.sql — core schema
--
-- Conventions
--   * UUID primary keys, generated by the database.
--   * created_at / updated_at on every mutable table, maintained by a trigger.
--   * Soft deletion (deleted_at) where a user might want their content back;
--     hard deletion where the brief promises irreversible erasure.
--   * Nested, non-queried structures are stored as jsonb. Anything filtered,
--     sorted or joined on gets a real column and an index.
--
-- Row Level Security lives in 0002_rls.sql. Content seeding in 0003_content.sql.
-- =============================================================================

create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- Shared helpers
-- -----------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =============================================================================
-- Reference content
--
-- The application reads curriculum content from typed TypeScript modules for
-- speed and offline caching (see docs/DECISIONS.md, ADR-003). These tables hold
-- the same content, seeded from those modules, so administrators can edit it
-- and so future tooling can query it.
-- =============================================================================

create table if not exists public.sectors (
  id            text primary key,
  name          text not null,
  description   text not null default '',
  caution       text,
  keywords      jsonb not null default '[]'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists public.skills (
  id            text primary key,
  name          text not null,
  dimension     text not null check (dimension in ('savoir-faire', 'savoir-etre', 'reflexion', 'communication')),
  description   text not null default '',
  keywords      jsonb not null default '[]'::jsonb,
  sector_ids    jsonb not null default '[]'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists skills_dimension_idx on public.skills (dimension);

create table if not exists public.career_paths (
  id              text primary key,
  slug            text not null unique,
  name            text not null,
  summary         text not null default '',
  description     text not null default '',
  audience        jsonb not null default '[]'::jsonb,
  outcomes        jsonb not null default '[]'::jsonb,
  prerequisites   jsonb not null default '[]'::jsonb,
  sector_ids      jsonb not null default '[]'::jsonb,
  skill_ids       jsonb not null default '[]'::jsonb,
  level           text not null check (level in ('debutant', 'intermediaire', 'avance')),
  featured        boolean not null default false,
  sort_order      integer not null default 0,
  estimated_hours integer not null default 0,
  icon            text not null default 'BookOpen',
  caution         text,
  published       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists career_paths_published_idx on public.career_paths (published, sort_order);

create table if not exists public.roadmap_stages (
  id                 text primary key,
  path_id            text not null references public.career_paths (id) on delete cascade,
  sort_order         integer not null,
  name               text not null,
  objective          text not null,
  skill_ids          jsonb not null default '[]'::jsonb,
  estimated_minutes  integer not null default 0,
  resource_ids       jsonb not null default '[]'::jsonb,
  practical_exercise jsonb not null default '{}'::jsonb,
  checklist          jsonb not null default '[]'::jsonb,
  reflection         text not null default '',
  evidence           text not null default '',
  knowledge_check    jsonb not null default '[]'::jsonb,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  unique (path_id, sort_order)
);

create index if not exists roadmap_stages_path_idx on public.roadmap_stages (path_id, sort_order);

create table if not exists public.roadmap_items (
  id           text primary key,
  stage_id     text not null references public.roadmap_stages (id) on delete cascade,
  path_id      text not null references public.career_paths (id) on delete cascade,
  sort_order   integer not null,
  title        text not null,
  description  text,
  minutes      integer not null default 0,
  kind         text not null check (kind in ('lecture', 'pratique', 'reflexion', 'evaluation')),
  resource_ids jsonb not null default '[]'::jsonb,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists roadmap_items_stage_idx on public.roadmap_items (stage_id, sort_order);

create table if not exists public.learning_resources (
  id              text primary key,
  title           text not null,
  provider        text not null,
  url             text not null,
  description     text not null default '',
  language        text not null check (language in ('fr', 'en', 'bm', 'multi')),
  skill_ids       jsonb not null default '[]'::jsonb,
  sector_ids      jsonb not null default '[]'::jsonb,
  format          text not null,
  level           text not null check (level in ('debutant', 'intermediaire', 'avance')),
  minutes         integer not null default 0,
  connectivity    text not null check (connectivity in ('offline', 'low', 'medium', 'high')),
  mobile_friendly boolean not null default true,
  offline_capable boolean not null default false,
  cost            text not null check (cost in ('gratuit', 'freemium')),
  certificate     boolean not null default false,
  quality_notes   text not null default '',
  -- 'verified' may only be set by a human who actually opened the link.
  verification    text not null default 'pending' check (verification in ('verified', 'pending', 'broken')),
  last_reviewed   date,
  archived        boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  -- A link cannot claim verification without the date it was verified.
  constraint learning_resources_verified_needs_date
    check (verification <> 'verified' or last_reviewed is not null)
);

create index if not exists learning_resources_verification_idx on public.learning_resources (verification, archived);
create index if not exists learning_resources_language_idx on public.learning_resources (language, level);

create table if not exists public.roadmap_resource_links (
  id          uuid primary key default gen_random_uuid(),
  stage_id    text not null references public.roadmap_stages (id) on delete cascade,
  resource_id text not null references public.learning_resources (id) on delete cascade,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  unique (stage_id, resource_id)
);

create table if not exists public.practical_projects (
  id                    text primary key,
  slug                  text not null unique,
  title                 text not null,
  path_id               text not null references public.career_paths (id) on delete cascade,
  difficulty            text not null check (difficulty in ('facile', 'moyen', 'exigeant')),
  simulated             boolean not null default false,
  estimated_minutes     integer not null default 0,
  scenario              text not null,
  objective             text not null,
  instructions          jsonb not null default '[]'::jsonb,
  deliverable           text not null,
  skill_ids             jsonb not null default '[]'::jsonb,
  evaluation_checklist  jsonb not null default '[]'::jsonb,
  portfolio_description text not null default '',
  offline_friendly      boolean not null default true,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists practical_projects_path_idx on public.practical_projects (path_id);

create table if not exists public.interview_questions (
  id                    text primary key,
  category              text not null,
  question              text not null,
  why_asked             text not null default '',
  what_they_listen_for  jsonb not null default '[]'::jsonb,
  trap                  text not null default '',
  structure             jsonb not null default '[]'::jsonb,
  sector_ids            jsonb not null default '[]'::jsonb,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists interview_questions_category_idx on public.interview_questions (category);

-- Admin edits are stored as an overlay so the seeded content stays intact and
-- an edit can always be reverted. See docs/CONTENT_MODEL.md.
create table if not exists public.content_overrides (
  id         uuid primary key default gen_random_uuid(),
  kind       text not null check (kind in ('resource', 'path', 'project', 'skill', 'sector')),
  ref_id     text not null,
  payload    jsonb not null,
  archived   boolean not null default false,
  updated_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (kind, ref_id)
);

-- Audit trail for content review — who checked what, and when.
create table if not exists public.content_reviews (
  id          uuid primary key default gen_random_uuid(),
  kind        text not null,
  ref_id      text not null,
  reviewer_id uuid,
  outcome     text not null check (outcome in ('verified', 'broken', 'archived', 'updated')),
  notes       text not null default '',
  created_at  timestamptz not null default now()
);

create index if not exists content_reviews_ref_idx on public.content_reviews (kind, ref_id, created_at desc);

-- =============================================================================
-- User data
-- =============================================================================

create table if not exists public.profiles (
  id                      uuid primary key references auth.users (id) on delete cascade,
  email                   text not null,
  display_name            text not null default '',
  locale                  text not null default 'fr',
  is_admin                boolean not null default false,
  onboarding_completed_at timestamptz,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  deleted_at              timestamptz
);

create index if not exists profiles_email_idx on public.profiles (lower(email));

create table if not exists public.user_preferences (
  user_id        uuid primary key references public.profiles (id) on delete cascade,
  hours_per_week integer not null default 5 check (hours_per_week between 1 and 60),
  connectivity   text not null default 'correcte' check (connectivity in ('rare', 'limitee', 'correcte', 'bonne')),
  device         text not null default 'smartphone',
  learning_style text not null default 'pratique',
  locale         text not null default 'fr',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists public.onboarding_responses (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.profiles (id) on delete cascade,
  answers      jsonb not null,
  completed_at timestamptz not null default now(),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.profile_skill_assessments (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  skill_id    text not null,
  -- 'proven' comes from finished work; 'declared' from self-assessment.
  evidence    text not null check (evidence in ('proven', 'learning', 'declared')),
  source      text not null default 'progress',
  updated_at  timestamptz not null default now(),
  created_at  timestamptz not null default now(),
  unique (user_id, skill_id)
);

create table if not exists public.user_roadmaps (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.profiles (id) on delete cascade,
  path_id      text not null,
  is_primary   boolean not null default false,
  started_at   timestamptz not null default now(),
  completed_at timestamptz,
  archived_at  timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (user_id, path_id)
);

create index if not exists user_roadmaps_user_idx on public.user_roadmaps (user_id, is_primary desc);

create table if not exists public.user_progress (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.profiles (id) on delete cascade,
  path_id      text not null,
  stage_id     text not null,
  item_id      text not null,
  completed_at timestamptz not null default now(),
  created_at   timestamptz not null default now(),
  -- Makes replaying a queued offline completion idempotent.
  unique (user_id, item_id)
);

create index if not exists user_progress_user_path_idx on public.user_progress (user_id, path_id);

create table if not exists public.user_notes (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles (id) on delete cascade,
  scope      text not null check (scope in ('stage', 'project', 'employer', 'reflection')),
  ref_id     text not null,
  body       text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, scope, ref_id)
);

create table if not exists public.saved_resources (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  resource_id text not null,
  rating      text check (rating in ('useful', 'not-useful')),
  saved_at    timestamptz not null default now(),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (user_id, resource_id)
);

create table if not exists public.weekly_plans (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.profiles (id) on delete cascade,
  week_start    date not null,
  path_id       text not null,
  objective     text not null default '',
  hours_target  integer not null default 5,
  generated_at  timestamptz not null default now(),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (user_id, week_start)
);

create index if not exists weekly_plans_user_week_idx on public.weekly_plans (user_id, week_start desc);

create table if not exists public.weekly_tasks (
  id           uuid primary key default gen_random_uuid(),
  plan_id      uuid not null references public.weekly_plans (id) on delete cascade,
  user_id      uuid not null references public.profiles (id) on delete cascade,
  title        text not null,
  description  text,
  kind         text not null,
  minutes      integer not null default 0,
  day          smallint not null check (day between 0 and 6),
  path_id      text,
  stage_id     text,
  item_id      text,
  project_id   text,
  completed_at timestamptz,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists weekly_tasks_plan_idx on public.weekly_tasks (plan_id, day, sort_order);

create table if not exists public.user_projects (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references public.profiles (id) on delete cascade,
  project_id     text not null,
  started_at     timestamptz not null default now(),
  completed_at   timestamptz,
  work           text not null default '',
  evidence_url   text,
  reflection     text not null default '',
  checklist_done jsonb not null default '[]'::jsonb,
  in_portfolio   boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (user_id, project_id)
);

create index if not exists user_projects_user_idx on public.user_projects (user_id, completed_at desc nulls last);

create table if not exists public.portfolio_entries (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  project_id  text,
  title       text not null,
  description text not null default '',
  evidence_url text,
  skill_ids   jsonb not null default '[]'::jsonb,
  -- Simulated exercises must stay labelled as such wherever they are shown.
  simulated   boolean not null default false,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists portfolio_entries_user_idx on public.portfolio_entries (user_id, sort_order);

-- -----------------------------------------------------------------------------
-- Job analysis
-- -----------------------------------------------------------------------------

create table if not exists public.job_descriptions (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid references public.profiles (id) on delete cascade,
  job_title  text not null default '',
  company    text,
  raw_text   text not null,
  source     text not null default 'paste',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists job_descriptions_user_idx on public.job_descriptions (user_id, created_at desc);

create table if not exists public.job_requirements (
  id                 uuid primary key default gen_random_uuid(),
  job_description_id uuid not null references public.job_descriptions (id) on delete cascade,
  kind               text not null check (kind in (
                       'responsabilite', 'competence-requise', 'competence-appreciee',
                       'langue', 'outil', 'formation', 'experience', 'comportement')),
  label              text not null,
  evidence           text not null default '',
  skill_id           text,
  confidence         numeric(3, 2) not null default 0.50,
  created_at         timestamptz not null default now()
);

create index if not exists job_requirements_description_idx on public.job_requirements (job_description_id, kind);

create table if not exists public.job_analyses (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid references public.profiles (id) on delete cascade,
  job_description_id uuid not null references public.job_descriptions (id) on delete cascade,
  extraction         jsonb not null,
  comparison         jsonb,
  answers            jsonb not null default '{}'::jsonb,
  readiness_score    integer check (readiness_score between 0 and 100),
  -- 'rules' or 'rules+ai' — recorded so a user can tell how it was produced.
  engine             text not null default 'rules',
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists job_analyses_user_idx on public.job_analyses (user_id, created_at desc);

create table if not exists public.skill_gaps (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  label       text not null,
  skill_id    text,
  occurrences integer not null default 1,
  status      text not null default 'todo' check (status in ('todo', 'learning', 'addressed')),
  path_id     text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (user_id, label)
);

-- -----------------------------------------------------------------------------
-- Job readiness workspaces
-- -----------------------------------------------------------------------------

create table if not exists public.value_propositions (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles (id) on delete cascade,
  input      jsonb not null,
  output     jsonb not null,
  engine     text not null default 'rules',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.interview_practice_answers (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  question_id text not null,
  body        text not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (user_id, question_id)
);

create table if not exists public.star_examples (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles (id) on delete cascade,
  label      text not null default '',
  situation  text not null default '',
  task       text not null default '',
  action     text not null default '',
  result     text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.confidence_work (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references public.profiles (id) on delete cascade,
  feared_question text not null default '',
  prepared_answer text not null default '',
  evidence        text not null default '',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.cv_profiles (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  full_name   text not null default '',
  headline    text not null default '',
  summary     text not null default '',
  phone       text not null default '',
  city        text not null default '',
  experiences jsonb not null default '[]'::jsonb,
  education   jsonb not null default '[]'::jsonb,
  languages   jsonb not null default '[]'::jsonb,
  skills      jsonb not null default '[]'::jsonb,
  tools       jsonb not null default '[]'::jsonb,
  projects    jsonb not null default '[]'::jsonb,
  extras      text not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.checklist_states (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.profiles (id) on delete cascade,
  checklist_id  text not null,
  done_item_ids jsonb not null default '[]'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (user_id, checklist_id)
);

create table if not exists public.employer_research (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.profiles (id) on delete cascade,
  company       text not null default '',
  notes         text not null default '',
  done_item_ids jsonb not null default '[]'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (user_id, company)
);

-- -----------------------------------------------------------------------------
-- Feedback and aggregate metrics
-- -----------------------------------------------------------------------------

create table if not exists public.feedback (
  id         uuid primary key default gen_random_uuid(),
  type       text not null check (type in ('idee', 'probleme', 'contenu', 'accessibilite', 'partenariat', 'autre')),
  message    text not null,
  -- Optional and only stored when the user asks for a reply.
  email      text,
  created_at timestamptz not null default now()
);

create index if not exists feedback_created_idx on public.feedback (created_at desc);

-- Counters only. No user id, no session id, nothing that could reconstruct an
-- individual's activity. See docs/PRIVACY.md.
create table if not exists public.metric_counters (
  event      text primary key,
  count      bigint not null default 0,
  updated_at timestamptz not null default now()
);

create or replace function public.increment_metric(metric_event text)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.metric_counters (event, count, updated_at)
  values (metric_event, 1, now())
  on conflict (event) do update
    set count = public.metric_counters.count + 1,
        updated_at = now();
$$;

-- -----------------------------------------------------------------------------
-- updated_at triggers
-- -----------------------------------------------------------------------------

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'sectors', 'skills', 'career_paths', 'roadmap_stages', 'roadmap_items',
    'learning_resources', 'practical_projects', 'interview_questions',
    'content_overrides', 'profiles', 'user_preferences', 'onboarding_responses',
    'profile_skill_assessments', 'user_roadmaps', 'user_notes', 'saved_resources',
    'weekly_plans', 'weekly_tasks', 'user_projects', 'portfolio_entries',
    'job_descriptions', 'job_analyses', 'skill_gaps', 'value_propositions',
    'interview_practice_answers', 'star_examples', 'confidence_work',
    'cv_profiles', 'checklist_states', 'employer_research'
  ]
  loop
    execute format('drop trigger if exists set_updated_at on public.%I', table_name);
    execute format(
      'create trigger set_updated_at before update on public.%I
         for each row execute function public.set_updated_at()',
      table_name
    );
  end loop;
end;
$$;

-- -----------------------------------------------------------------------------
-- Create a profile row automatically for every new auth user.
-- -----------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;

  insert into public.user_preferences (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
